pipeline_id: "streamdiffusionv2"
pipeline_name: "StreamDiffusionV2"
pipeline_description: >
  A streaming pipeline and autoregressive video diffusion model from the creators of the original
  StreamDiffusion project. The model is trained using Self-Forcing on Wan2.1 1.3b with modifications
  to support streaming.
docs_url: "https://github.com/daydreamlive/scope/blob/main/src/scope/core/pipelines/streamdiffusionv2/docs/usage.md"
estimated_vram_gb: 20.0
requires_models: true
supports_lora: true
supports_vace: true

supports_cache_management: true
supports_quantization: true
min_dimension: 16
modified: true

denoising_steps: [750, 250]
noise_scale: 0.7
noise_controller: true
input_size: 4

modes:
  text:
    height: 512
    width: 512
    denoising_steps: [1000, 750]
  video:
    default: true
